react-router-dom
M2-App/web-m2-app pull request #5
Opened 2024-05-07 21:40 UTC by Caleb-Nieto

### Feature / Bug Description
Adds react-router-dom dependency

### Solution
reac-router-dom dependency added and BrowserRoutes, Routes and Route component added on main.tsx file

### Notes
Any note

### Tickets
[WMA-18] (https://cdentalcaregroup.atlassian.net/browse/WMA-18)

### Screenshots / Screencasts
![image](https://github.com/M2-App/web-m2-app/assets/133397335/04e89967-dde6-48fd-87c6-648aad0035cf)

2024-05-07 21:42 UTC, imadiaz requested changes
please merge first this PR and then rebase from develop to have just the changes about this PR and not both PR's https://github.com/M2-App/web-m2-app/pull/4

2024-05-09 16:33 UTC, imadiaz commented on src/App.tsx
> +export default App;
i think that you don't need ;

2024-05-09 16:34 UTC, imadiaz reviewed
can u add a video navigating between the options?

2024-05-09 16:42 UTC, imadiaz commented on src/pages/routes/Routes.tsx
> +export class Route {
maybe we can extract this code in a class 

/routes/models/route.tsx
 and move just the class there

2024-05-09 16:42 UTC, Caleb-Nieto commented
Of course!! 
 https://github.com/M2-App/web-m2-app/assets/133397335/d3e8d45a-8f3c-4c44-b0cd-a6e1ab8a4021

2024-05-09 16:43 UTC, imadiaz commented on src/pages/proofPages/proofPages.tsx
> +export const Page1 = () => {
Just to keep in mind once we add the pages, we can remove this mock pages

2024-05-09 16:44 UTC, Caleb-Nieto commented on src/pages/routes/Routes.tsx
> +export class Route {
Okay I like it!!

2024-05-09 16:44 UTC, Caleb-Nieto commented on src/App.tsx
> +export default App;
Okay!!

2024-05-09 16:46 UTC, Caleb-Nieto commented on src/pages/proofPages/proofPages.tsx
> +export const Page1 = () => {
Yeah! I will remember

2024-05-09 16:51 UTC, Caleb-Nieto commented
can you see the video?

2024-05-09 16:58 UTC, imadiaz approved these changes
lgtm

2024-05-09 16:59 UTC, merged